# 기본 설정
title = '지진관측 채널'
theme = '2023dark' # 테마
baseURL = 'http://example.org/' # 기본 URL

# 고급 설정
paginate = 10
disableKinds = ['RSS', 'taxonomy'] # RSS 비활성화
ignoreErrors = ["error-disable-taxonomy"] # taxonomy 비활성화 오류 예외
languageCode = 'ko-KR' # 사이트 언어 설정 (자동번역 도움됨)
defaultContentLanguage = 'ko' # 다국어 처리 기본값 언어
timeZone = 'Asia/Seoul' # 시간대 설정
hasCJKLanguage = true # CJK 언어 감지 (글자 갯수 셀때 도움됨)
enableRobotsTXT = true # 크롤링 봇 허용 (SEO 검색 향상)
enableInlineShortcodes = true # 인라인 단축코드 사용 (기본값 false, false시 단일 줄에서만 가능함)

[frontmatter]
lastmod = [':fileModTime', ':default']

# 사이트 변수
[params]
brandName = "지진관측 채널 Jpn Kor Earthquake"
discordInviteURL = "https://discord.gg/RDrkKNnYC3"
orgEmail = "org@jpkreq.com"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.extensions]
definitionList = true # 단어 정의
footnote = true # 각주
linkify = true # 자동 링크 감지
linkifyProtocol = 'https'
strikethrough = true # 취소줄 파싱
table = true # 테이블 구현
taskList = true # 체크박스 목록 구현
typographer = true # 글자로 특수기호 대체

[markup.goldmark.renderer]
unsafe = true # HTML 코드 삽입 허용

[markup.goldmark.parser]
autoHeadingID = true # 제목 앵커 구현
autoHeadingIDType = 'github' # 앵커 링크 스타일
# wrapStandAloneImageWithinParagraph = true

[markup.goldmark.parser.attribute] # 마크다운에서 class 제어 가능
block = true
title = true

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true
